<?xml version="1.0"?>

<robot name="ugv_robot"
    xmlns:xacro="http://www.ros.org/wiki/xacro"
    xmlns:interface="http://www.ros.org/wiki/xacro">
    
    <xacro:include filename="$(find ugv_description)/urdf/ugv_wheel.urdf.xacro" />
    
    <!-- Properties (Constants) -->
    <xacro:property name="M_PI" value="3.14159"/>
    
    <xacro:property name="base_size_x" value="2.5" />
    <xacro:property name="base_size_y" value="1" />
    <xacro:property name="base_size_z" value="1.0" />
    
    <xacro:property name="wheel_radius" value="0.08" />
    <xacro:property name="wheel_length" value="0.05" />
    <!-- <xacro:property name="wheel_size_y" value="0.0825" /> -->
    
    <!--    <xacro:property name="wheel_offset_y" value="${(total_width - wheel_size_y) / 2}" />-->
    <!-- <xacro:property name="wheel_offset_y" value="0.48" /> -->
    <xacro:property name="wheel_offset_x" value="0.2" />
    <xacro:property name="wheel_offset_y" value="0.48" />
    <xacro:property name="wheel_offset_z_from_base_link" value="-0.72" />
      
    
    <link name="ugv_base_link">
        <!-- <inertial>
            <mass value="20.0" />
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <inertia ixx="0.13" ixy="0.0" ixz="0.0"
                        iyy="0.13" iyz="0.0" 
                        izz="0.13" />
        </inertial> -->

        <inertial>
            <mass value="10.0" />
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <!-- <inertia ixx="1.4" ixy="0.0" ixz="0.0"
                        iyy="5.5" iyz="0.0" 
                        izz="5.5" /> -->
            <inertia ixx="0.13" ixy="0.0" ixz="0.0"
                        iyy="0.13" iyz="0.0" 
                        izz="0.13" />
        </inertial>
        
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <!-- -0.255 -->
            <geometry>
                <!--<box size="${base_size_x} ${base_size_y} ${base_size_z}" />-->
                <!-- <mesh filename="package://ugv_description/meshes/jasmine_ugv/jasmine_ugv.dae" scale="3 3 3"/> -->
                <mesh filename="package://ugv_description/meshes/lr90.dae" scale="1 1 1"/>
            </geometry>
            
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
            </geometry>
        </collision>
    </link>

    <link name="top_link">
        <inertial>
            <mass value="0.5" />
            <origin xyz="0.00 0.00 0.5" rpy="0 1.5708 0" />
            <inertia ixx="0.08" ixy="0.0" ixz="0.0"
                        iyy="0.08" iyz="0.0" 
                        izz="0.08" />
        </inertial>
        
        <visual>
            <!-- <origin xyz="-0.00 0.00 0.5" rpy="0 0 0" /> -->
            <origin xyz="-0.50 0.00 0.5" rpy="0 0 0" />
            <geometry>
                <!--<box size="${base_size_x} ${base_size_y} ${base_size_z}" />-->
                <!-- <mesh filename="package://ugv_description/meshes/apriltag/apriltag.dae" scale="1 1 1"/> -->
                <mesh filename="package://ugv_description/meshes/mix2/mix2.dae" scale="1 1 1"/>
                <!-- <mesh filename="package://ugv_description/meshes/emb_apriltag/emb_apriltag.dae" scale="1 1 1"/> -->
                <!-- <mesh filename="package://ugv_description/meshes/embed_apriltag/embed_apriltag.dae" scale="1 1 1"/> -->
            </geometry>
            
            
        </visual>
        
        <collision>
            <origin xyz="-0.50 0.00 0.5" rpy="0 0 0" />
            <geometry>
                <box size="1 1 0.02" />
            </geometry>
        </collision>
    </link>

    <joint name="base_to_top" type="fixed">
        <parent link="ugv_base_link"/>
        <child link="top_link"/>
    </joint>
    
    
    <!--	Add wheels using the hlugv_wheel macro-->
    
    <xacro:ugv_wheel parent="ugv_base_link" prefix="left_rear" offset_x= "-${wheel_offset_x}" offset_y = "${wheel_offset_y}" offset_z = "${wheel_offset_z_from_base_link}" 
            wheel_radius="${wheel_radius}" wheel_size_y="${wheel_length}"/>
    <xacro:ugv_wheel parent="ugv_base_link" prefix="left_middle" offset_x= "0" offset_y = "${wheel_offset_y}" offset_z = "${wheel_offset_z_from_base_link}" 
            wheel_radius="${wheel_radius}" wheel_size_y="${wheel_length}"/>
    <xacro:ugv_wheel parent="ugv_base_link" prefix="left_front" offset_x= "${wheel_offset_x}" offset_y = "${wheel_offset_y}" offset_z = "${wheel_offset_z_from_base_link}" 
            wheel_radius="${wheel_radius}" wheel_size_y="${wheel_length}"/>
    
    <xacro:ugv_wheel parent="ugv_base_link" prefix="right_rear" offset_x= "-${wheel_offset_x}" offset_y = "-${wheel_offset_y}" offset_z = "${wheel_offset_z_from_base_link}" 
            wheel_radius="${wheel_radius}" wheel_size_y="${wheel_length}"/>
    <xacro:ugv_wheel parent="ugv_base_link" prefix="right_middle" offset_x= "0" offset_y = "-${wheel_offset_y}" offset_z = "${wheel_offset_z_from_base_link}" 
            wheel_radius="${wheel_radius}" wheel_size_y="${wheel_length}"/>  
    <xacro:ugv_wheel parent="ugv_base_link" prefix="right_front" offset_x= "${wheel_offset_x}" offset_y = "-${wheel_offset_y}" offset_z = "${wheel_offset_z_from_base_link}" 
            wheel_radius="${wheel_radius}" wheel_size_y="${wheel_length}"/>   

    
     

    


    <!-- <xacro:ugv_ball parent="ugv_base_link" prefix="rear_ball" offset_x= "-0.7" offset_y = "0" offset_z = "${wheel_offset_z_from_base_link}" 
            wheel_radius="${wheel_radius}"/>        -->
    <!-- <xacro:ugv_wheel parent="ugv_base_link" prefix="rear_wheel" offset_x= "-0.7" offset_y = "0" offset_z = "${wheel_offset_z_from_base_link}" 
            reflect="1" wheel_radius="${wheel_radius}" wheel_size_y="${wheel_length}"/> -->
    
    <!-- <gazebo reference="ugv_base_link">
        <material>HLUGV/Green</material>
        <material>  
            <ambient>0.19225 0.19225 0.19225 1.0</ambient>  
            <diffuse>0.50754 0.50754 0.50754 1.0</diffuse>  
            <specular>0.508273 0.508273 0.508273 1.0</specular>  
            <emissive>0.0 0.0 0.0 0.0</emissive>  
        </material>
    </gazebo> -->

    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>50</updateRate>
            <leftJoint>left_middle_wheel_joint</leftJoint>
            <rightJoint>right_middle_wheel_joint</rightJoint>
            <wheelSeparation>0.96</wheelSeparation>
            <wheelDiameter>0.16</wheelDiameter>
            <torque>5000</torque>
            <commandTopic>/ugv/cmd_vel</commandTopic>
            <robotBaseFrame>ugv_base_link</robotBaseFrame>
            <legacyMode>false</legacyMode>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <publishWheelTF>true</publishWheelTF>
            <publishWheelJointState>true</publishWheelJointState>
        </plugin>
        

        <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>30.0</updateRate>
            <bodyName>ugv_base_link</bodyName>
            <topicName>ugv_ground_truth/state</topicName>
            <gaussianNoise>0.0</gaussianNoise>
            <frameName>world</frameName>
            <xyzOffsets>0 0 0</xyzOffsets>
            <rpyOffsets>0 0 0</rpyOffsets>
        </plugin>

    </gazebo>     
        
    
</robot>
